### ISSUE TITLE
impl activity meta generate and cache

### ISSUE THREAD

**Issue by wsky** [wsky/pacman#4]
``` java
protected void cacheMetadata(MetadataCache cache);
```

``` java
public static void cacheRootMetadata(Activity activity, LocationReferenceEnvironment hostEnvironment) {
        activity.initializeAsRoot(hostEnvironment);
        processActivityTree(activity, 0);
    }
```
- [ ] default dynamic generate
- [x] custom cache via override
- [x] activity tree process
- [x] visibility design:
  - LocationReferenceEnvironment: locationReference visibility
  - ActivityMembers: activity visibility

**Comment by wsky** [comment]
activity meta, tree and relationship

```
activity-root activity-parent: { implEnv, publicEnv, ...}
         /|\     /|\                       /|\
          |       |                         |
          activity: { implEnv, publicEnv, parentEnv, [runtimeArgument...], [variable...] }
             /|\                                        /|\                     /|\
              |                                          |                       |
        [activity-child, ...]              [argumentExpression, ...]  [variableDefaultValue, ...]
```

**Comment by wsky** [comment]
activity tree processing should include argument/variable's expression

**Comment by wsky** [comment]
activity visibility

```
activity#1 ----> activity#2 ----> activity#3
                   |
                  \|/
               activity#2-1 ----> activity#2-2
```

members(A): [1,2,3]
members(B) of activity#2: [2-1,2-2], 
activity#2 was parent of B

**Comment by wsky** [comment]
``` java
root = new Activity() {
            public Activity child = ActivityMetadataTest.this.child;
            public InArgument in = ActivityMetadataTest.this.in;
            public OutArgument out = new OutArgument();
            public Variable var = ActivityMetadataTest.this.var;
            private Variable inner = ActivityMetadataTest.this.inner;

            @Override
            protected void cacheMetadata(ActivityMetadata metadata) {
                super.cacheMetadata(metadata);
                metadata.bindAndAddArgument(this.in, new RuntimeArgument("in", Integer.class, ArgumentDirection.In));
                metadata.bindAndAddArgument(this.out, new RuntimeArgument("out", Integer.class, ArgumentDirection.Out));
                metadata.addRuntimeVariable(this.var);
                metadata.addImplementationVariable(this.inner);
                metadata.addChild(this.child);
            }
        };
```

```
1 , displayName=root
    - 1#0 argument: in, direction=In
    - 1#1 argument: out, direction=Out
    - 1#2 variable: var, isPublic=true
    - 1#3 implVariable: inner, isPublic=false
    - 1-1 Literal, displayName=null
    - 2 Literal, displayName=null
    - 3 Literal, displayName=null
    - 4 If, displayName=if
        - 4#0 argument: Condition, direction=In
        - 5 Literal, displayName=null
        - 6 WriteLine, displayName=writeLine
            - 6#0 argument: Text, direction=In
            - 7 Literal, displayName=null

```
